import os
from apps.paypal_templates.extra_code_or_config.paypal_account import \
    SANDBOX_ACCOUNT, SANDBOX_CLIENT_ID, SANDBOX_SECRET, \
    LIVE_ACCOUNT, LIVE_CLIENT_ID, LIVE_SECRET, SANDBOX_PERSONAL_ACCOUNT_NAME, \
    SANDBOX_PERSONAL_FIRST_NAME, SANDBOX_PERSONAL_LAST_NAME, \
    SANDBOX_PERSONAL_EMAIL, SANDBOX_PERSONAL_PASSWORD, \
    SANDBOX_BUSINESS_ACCOUNT_NAME, SANDBOX_BUSINESS_FIRST_NAME, \
    SANDBOX_BUSINESS_LAST_NAME, SANDBOX_BUSINESS_EMAIL, \
    SANDBOX_BUSINESS_PASSWORD, SANDBOX_CURRENCY, SANDBOX_LOCALE, \
    LIVE_CURRENCY, LIVE_LOCALE, SANDBOX_BASE_URL, LIVE_BASE_URL

'''
paypal_account.py should be hidden from a public github repository and setup
either locally or within a private github repository.   This file imports
the constants and creates an environment of constants depending upon if the
'PAYPAL_IS_LIVE' environment variable is set to "True" or "False".
(note these are strings!!!)

As an extra thought, on AWS it is possible to save secure information within
applications like secret manager or parameter store.   This would probably
be a better solution.
'''

# SET PAYPAL ENVIRONMENT
PAYPAL_IS_LIVE = (os.environ.get('PAYPAL_IS_LIVE', "False")=="True")
if PAYPAL_IS_LIVE:
    PAYPAL_ACCOUNT = LIVE_ACCOUNT
    PAYPAL_CLIENT_ID = LIVE_CLIENT_ID
    PAYPAL_SECRET = LIVE_SECRET
    PAYPAL_CURRENCY = LIVE_CURRENCY
    PAYPAL_LOCALE = LIVE_LOCALE
    PAYPAL_BASE_URL = LIVE_BASE_URL
    PAYPAL_LOGIN_DATA = None
else:
    PAYPAL_ACCOUNT = SANDBOX_ACCOUNT
    PAYPAL_CLIENT_ID = SANDBOX_CLIENT_ID
    PAYPAL_SECRET = SANDBOX_SECRET
    PAYPAL_CURRENCY = SANDBOX_CURRENCY
    PAYPAL_LOCALE = SANDBOX_LOCALE
    PAYPAL_BASE_URL = SANDBOX_BASE_URL
    PAYPAL_LOGIN_DATA = {
        'SANDBOX_PERSONAL_ACCOUNT_NAME': SANDBOX_PERSONAL_ACCOUNT_NAME,
        'SANDBOX_PERSONAL_FIRST_NAME': SANDBOX_PERSONAL_FIRST_NAME,
        'SANDBOX_PERSONAL_LAST_NAME': SANDBOX_PERSONAL_LAST_NAME,
        'SANDBOX_PERSONAL_EMAIL': SANDBOX_PERSONAL_EMAIL,
        'SANDBOX_PERSONAL_PASSWORD': SANDBOX_PERSONAL_PASSWORD,
        'SANDBOX_BUSINESS_ACCOUNT_NAME': SANDBOX_BUSINESS_ACCOUNT_NAME,
        'SANDBOX_BUSINESS_FIRST_NAME': SANDBOX_BUSINESS_FIRST_NAME,
        'SANDBOX_BUSINESS_LAST_NAME': SANDBOX_BUSINESS_LAST_NAME,
        'SANDBOX_BUSINESS_EMAIL': SANDBOX_BUSINESS_EMAIL,
        'SANDBOX_BUSINESS_PASSWORD': SANDBOX_BUSINESS_PASSWORD
    }
